version: '3'
# This example runs three servers, PostgreSQL, pgAdmin, and a frontEnd server

# Each service runs in a seperate container
services:
  shopping-db:
    container_name: shopping-db
    image: postgres:latest
    restart: always
    environment:
      DATABASE_HOST: shopping-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_PORT: 5432
      POSTGRES_DB: shopping
      PGDATA: /var/lib/postgresql/data
    ports:
      - "7432:5432"
    volumes:
      - pgdatasource:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgAdmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: fec@mail.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "8080:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - shopping-db

volumes:
  pgdatasource:
  pgadmin-data:

networks:
  default:
